# Generated by Django 5.2.8 on 2025-11-08 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obiect',
            fields=[
                ('id_obiect', models.AutoField(primary_key=True, serialize=False)),
                ('tip_obiect', models.CharField(max_length=100)),
                ('id_css', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('parola', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Rezervare',
            fields=[
                ('id_rez', models.AutoField(primary_key=True, serialize=False)),
                ('data_si_ora', models.DateTimeField()),
                ('obiect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rezervari', to='backend.obiect')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rezervari', to='backend.user')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'obiect', 'data_si_ora'), name='unique_rezervare_slot')],
            },
        ),
    ]
