# Generated by Django 5.2.8 on 2025-11-08 23:34

from datetime import timedelta

from django.db import migrations
from django.utils import timezone


def seed_initial_data(apps, schema_editor):
    User = apps.get_model('backend', 'User')
    Obiect = apps.get_model('backend', 'Obiect')
    Rezervare = apps.get_model('backend', 'Rezervare')

    user_specs = [
        {'email': 'alex@example.com', 'parola': 'parola_alex'},
        {'email': 'maria@example.com', 'parola': 'parola_maria'},
    ]
    obiect_specs = [
        {'tip_obiect': 'Birou inteligent', 'id_css': 'B1'},
        {'tip_obiect': 'Sala VR', 'id_css': 'V2'},
    ]

    users = {}
    for spec in user_specs:
        user, _ = User.objects.get_or_create(email=spec['email'], defaults={'parola': spec['parola']})
        users[spec['email']] = user

    obiecte = {}
    for spec in obiect_specs:
        obiect, _ = Obiect.objects.get_or_create(tip_obiect=spec['tip_obiect'], id_css=spec['id_css'])
        obiecte[spec['tip_obiect']] = obiect

    base_time = timezone.now()
    reservations = [
        (users['alex@example.com'], obiecte['Birou inteligent'], base_time),
        (users['maria@example.com'], obiecte['Sala VR'], base_time + timedelta(hours=2)),
        (users['alex@example.com'], obiecte['Sala VR'], base_time + timedelta(days=1)),
    ]

    for user, obiect, data_si_ora in reservations:
        Rezervare.objects.get_or_create(user=user, obiect=obiect, data_si_ora=data_si_ora)


def unseed_initial_data(apps, schema_editor):
    User = apps.get_model('backend', 'User')
    Obiect = apps.get_model('backend', 'Obiect')
    Rezervare = apps.get_model('backend', 'Rezervare')

    Rezervare.objects.filter(
        user__email__in=['alex@example.com', 'maria@example.com']
    ).delete()
    Obiect.objects.filter(
        tip_obiect__in=['Birou inteligent', 'Sala VR']
    ).delete()
    User.objects.filter(
        email__in=['alex@example.com', 'maria@example.com']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_initial_data, unseed_initial_data),
    ]
