# Generated by Django 5.2.8 on 2025-11-08 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_seed_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obiect',
            name='id_css',
            field=models.CharField(max_length=255),
        ),
    ]
