# Generated by Django 5.2.8 on 2025-11-09 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_obiect_id_css'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rezervare',
            name='unique_rezervare_slot',
        ),
        migrations.AddConstraint(
            model_name='rezervare',
            constraint=models.UniqueConstraint(fields=('obiect', 'data_si_ora'), name='unique_rezervare_slot'),
        ),
    ]
