# Generated by Django 5.2.8 on 2025-11-09 01:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_rezervare_unique_rezervare_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezervare',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
